### ISSUE TITLE
Screenshots please

### ISSUE THREAD

**Issue by luzpaz** [waveform80/picademy_worksheets#1]

**Comment by waveform80** [comment]
Which worksheet? And screenshots of what precisely?

**Comment by luzpaz** [comment]
Perhaps a screenshot of each frontpage worksheet ?

**Comment by waveform80** [comment]
Oh I see - I was trying to keep the final PDFs (and any derivatives) out of the repository as they're effectively build artefacts, but I suppose this could serve as a distribution point for them. I only wish Scribus had some form of command line for auto-building of PDFs so I could construct a Makefile for them (unfortunately it's a [long standing issue](http://bugs.scribus.net/view.php?id=238) (10 years!) in their tracker).

Would the PDFs for each worksheet suffice (printer target, lossless compression, 300dpi)? Frankly it's easier to produce those than a screenshot.

**Comment by luzpaz** [comment]
@waveform80 What I'm saying is that you can add screenshots of the .sla front pages to the README and it can help orient people who arrive here because your project came up in a 'Scribus' github-wide search. 

As for the long standing issue, yes, it's no small task i would assume. There have been some command line developments this year that allow to run scribus scripts via command line. In fact there is a [patch on the bug tracker that allows one to pass variables via the Scribus CLI to python scripts](http://bugs.scribus.net/view.php?id=13311)

**Comment by waveform80** [comment]
Fixed in 17ecdfbbf66271dbe99ad5ea24e2c85ff5e90523
